Parrallel timeseries analysis in slurm
valeriupredoi/bgcval2 pull request #120
Opened 2023-11-24 15:48 UTC by ledm

#closes 118

It's looking like this script is working now. 

This PR adds a slurm queue based batch parallel processing of single job timeseries tool.

It's got the following features:
- Loads from existing `input_yaml` files.
- Run with a single command
- Fully parallelises the slowest part of the `analysis_comparison` tool: the single job analysis.
- Won't submit the same jobID if it's already existing*

* However, if two analyses call the same jobID with different suites (ie one has `bgc` and one has `physics`), it will only run the first one. 

Need to do:
- Documentation in README.md
- Is it @DrYool proof?

2023-11-24 16:11 UTC, valeriupredoi requested changes
hey bud, nice and fast turnaround - I am a bit concerned about the actual submission process (call to `subprocess`, see me comment) - I'd also think you should add job requirements, no? Also, I'd rename it to batch so and so, since it's not quite parallel-parallel :grin:

2023-11-24 16:11 UTC, valeriupredoi commented on bgcval2/parrellel_timeseries.py
> +            command1 = subprocess.Popen(command_txt)
I'd defo encase this in a try/except with except fishing for some key elements in stderr, or just printing the whole stderr to screen; if you don't pipe stderr as out it'll be hidden, and the user won't know why their jobs have not been submitted when they thought they have

2023-11-24 16:11 UTC, valeriupredoi commented on setup.py
> +            'parrallel_timeseries = bgcval2.parrellel_timeseries:main',
I'd name it `batch_timeseries` -> it's not exactly parallel as in compute parallel (eg with MPI or multiprocessing/Pool)

2023-11-24 16:13 UTC, valeriupredoi commented
oh and also - this things really do deserve a test, not thru and thru with SLURM submission, but everything up to that. I can write the test when it's about ready :+1:

2023-11-27 10:58 UTC, ledm commented on .gitignore
> +.idea/vcs.xml
It's some auto generated code from a windows IDE. I don't want it in the repository.

2023-11-27 13:53 UTC, valeriupredoi commented on .gitignore
> +.idea/vcs.xml
is it just you that produces it or anyone else running bgcval2?

2023-11-27 14:00 UTC, valeriupredoi requested changes
let's make sure the piping is done correctly; also, have you tried this in practice? We don't need any special `env` to pass to `sbatch` do we? Like any special environment variables

2023-11-27 14:00 UTC, valeriupredoi commented on bgcval2/batch_timeseries.py
> +            command1 = subprocess.Popen(command_txt)
```suggestion
            command1 = subprocess.Popen(
                  command_txt,
                  stdout=subprocess.PIPE,
                  stderr=subprocess.STDOUT,
            )
```

2023-11-27 15:25 UTC, ledm commented on .gitignore
> +.idea/vcs.xml
It's generated by jetbrains when you open a python repository. I'm not sure I even want to use jetbrains.

2023-11-27 15:31 UTC, valeriupredoi commented on .gitignore
> +.idea/vcs.xml
OK this is getting rabbit-holey :rabbit: Leave it there, it's not gonna kill any rabbits :grin:

2023-11-27 15:39 UTC, ledm commented
> let's make sure the piping is done correctly; also, have you tried this in practice? We don't need any special `env` to pass to `sbatch` do we? Like any special environment variables

I've been using this for a few days and it works on jasmin. Your amendment to the subprocess also works too.

 If batch_timeseries fails you get normal python errors. If it fails inside inside the sbatch script, then you get error messages in the places that we tell it to fail.

2023-11-27 15:41 UTC, valeriupredoi commented
yeh that's how we want it to behave, so stdout can be piped to eg a file. Looks good, bud! Let me write a test for it!

2023-11-27 15:57 UTC, ledm commented on README.md
> +compare -h
```suggestion
```

2023-11-27 16:00 UTC, ledm commented
The next question I have:
- Do we want to make this the default behaviour? This would mean that we run this script from inside `analysis_compare` when the `-s` flag is absent instead of calling the `analysis_timeseries` command?

2023-11-27 16:09 UTC, valeriupredoi commented
@ledm I added some test gubbins, make sure to pull or merge so there are no conflictseses

2023-11-27 16:43 UTC, ledm commented
The logo in the README points towards a file on the main branch, but of course it's not available yet until this PR is merged.

2023-11-28 10:42 UTC, ledm commented on bgcval2/batch_timeseries.py
> +def submits_lotus(compare_yml, config_user, dry_run=False):
We're not actually using config_user here, but I'm keeping it for completeness, just in case.

2023-11-28 10:43 UTC, ledm commented on README.md
> +sbatch -J u-aa111 --error=logs/u-aa111.err --output=logs/u-aa111.out lotus_timeseries.sh u-aa111 kmf physics bgc
```suggestion
sbatch -J jobID --error=logs/jobID .err --output=logs/jobID .out lotus_timeseries.sh jobID  kmf physics bgc
```

2023-11-28 10:44 UTC, ledm commented on README.md
> +The output and error messages will be in the `logs` directory which the jobID as the file prefix.
```suggestion
The output and error messages will be in the `logs` directory with the jobID as the file prefix.
```

2023-11-28 10:47 UTC, ledm commented on README.md
> +The analysis suites will be apended as a list to the end of the command.
```suggestion
The analysis suites will be appended as a list to the end of the command.
In order to reduce the chance of analysing the same jobID twice, `batch_timeseries`
checks whether a job exists, either currently running or in the queue before submitting.
If a jobID exists, it is not re-submitted. However, this means that
if two versions of the same jobID are submitted one after the other
with different suite lists (`kmf`, `physics`, `bgc`), then only the first 
set of suites will be run. 
```

2023-11-28 10:54 UTC, ledm commented on README.md
> +with the `-s` skip the `analysis_timeseries` section
```suggestion
with the `-s` argument to skip the `analysis_timeseries` section 
```

2023-11-28 10:55 UTC, ledm commented
Okay @valeriupredoi, I'm happy with this now.

2023-11-28 11:03 UTC, valeriupredoi commented
all good by me too, bud! Go ahead and merge when you good 🍺

2023-11-28 11:17 UTC, merged