Developments for TF AMOC analysis
valeriupredoi/bgcval2 pull request #136
Opened 2024-11-20 14:29 UTC by ledm

Tons of useful features and new analyses for the TerraFIRMA AMOC paper I'm writing.

2025-05-16 09:29 UTC, ledm commented
Hey @valeriupredoi, I'm about to start a new batch of development on bgcval. The starting point will be this branch,  so it would be good to merge this into Main.

2025-05-16 09:31 UTC, ledm commented
There are three main changes in one PR here:
- adapt code to new Lotus2 system
- several new fields and regions for the AMOC analysis
- added json to comparison reports.

2025-05-23 12:14 UTC, valeriupredoi commented
@ledm sorry bud, was travelling last week, let me have a looksee now :beer:

2025-05-23 14:33 UTC, valeriupredoi requested changes

2025-05-23 14:33 UTC, valeriupredoi commented on bgcval2/bgcvaltools/generic_map_legend.py
> +ncfn = 'mesh_mask_eORCA1_wrk.nc'
hey bud, where is this file? Running the tests fail because nobody knows where the file is :grin:

2025-06-16 13:36 UTC, valeriupredoi commented on bgcval2/bgcvaltools/generic_map_legend.py
> +ncfn = 'mesh_mask_eORCA1_wrk.nc'
the zero size barf means that's an empty array BTW, like `np.array([])`

2025-06-18 10:16 UTC, ledm commented on bgcval2/bgcvaltools/generic_map_legend.py
> +ncfn = 'mesh_mask_eORCA1_wrk.nc'
```
FAILED tests/integration/test_analysis_compare_end-end.py::test_run_analysis_compare - ValueError: zero-size array to reduction operation minimum which has no identity
FAILED tests/integration/test_analysis_compare_end-end.py::test_run_analysis_compare_with_skip_timeseries - FileNotFoundError: Data dir /home/runner/work/bgcval2/bgcval2/local_test/BGC_data/u-cp416debug does not contain any file that matches pattern /home/runner/work/bgcval2/bgcval2/local_test/BGC_data/u-cp416debug/nemo_u-cp416debugo_1y_*_grid-T.nc, NAME
```

It looks like it's struggling to find the dummy data. For me, there's nothing in the `bgcval2/local_test/BGC_data/u-cp416debug/` directory. 

I'm not sure how we did this before, but this is nothing that I've changed recently.

2025-06-18 12:58 UTC, ledm commented
Found it - it was a print statement that was not passing tests when running with staged data.

2025-06-18 13:16 UTC, valeriupredoi commented
awesome! Merge at will, all fine by me now - though, there is a bit of a latent issue somewhere in the script that generates the test data, `local_test/BGC_data/u-yyy` gets created with read-only permissions, so if you want to rerun the test you'll get a Permission error barf, not a problem if only for the test run, but it may be an issue if that creeps up in a normal user's run thou :beers:

2025-06-18 13:22 UTC, valeriupredoi commented
nevermind, that Permission error is in `main` too - so must be something ye olde; can forget about it for now, it's just weird since it's only for that `u-yyy` test suite. Meh :face_with_diagonal_mouth:

2025-06-18 14:08 UTC, ledm commented on bgcval2/bgcvaltools/generic_map_legend.py
> +    #    ncfn = 'mesh_mask_eORCA1_wrk.nc'
```suggestion
```

2025-06-18 14:21 UTC, ledm commented on bgcval2/bgcvaltools/generic_map_legend.py
> +ncfn = 'mesh_mask_eORCA1_wrk.nc'
It's passing tests, but merge isn't possible until your code change request is satisfied. Can you please accept?

2025-06-18 14:28 UTC, valeriupredoi approved these changes
whoops forgot about my stale review :beer:

2025-06-18 14:30 UTC, ledm commented
Thanks bud!

2025-06-18 14:30 UTC, merged