Automate nightly mass download
valeriupredoi/bgcval2 pull request #63
Opened 2022-09-22 16:11 UTC by ledm

A fairly complex set of changes that should allow us to automate nightly mass downloads. A lot more details in the issue #62.

Closes #62.

2022-09-22 16:12 UTC, ledm commented on bgcval2/analysis_compare.py
> -        dictionary = yaml.safe_load(openfile)
can't believe how long it took me to rename this variable.

2022-10-03 08:40 UTC, ledm commented
Note that I have not added any tools to delete the local copy of these data, once they've been downloaded. Perhaps we could add a system for that in here too.

2022-11-23 16:06 UTC, valeriupredoi commented
you wanna merge this branch, man? Or still working on it?

2022-11-24 14:20 UTC, ledm commented
yeah, I think so! Should be mergeable...

![image](https://user-images.githubusercontent.com/4180685/203806619-e7a8fbfa-aee3-4e38-8fd2-789d4bacf738.png)

2022-11-25 13:51 UTC, valeriupredoi requested changes
noice! Couple tiny wiggles from me, man :beer:

2022-11-25 13:51 UTC, valeriupredoi commented on bgcval2/download_from_mass.py
> +        shutil.copy(download_script_path, shared_file_path)
make sure you also `rmtree` what's not needed

2022-11-25 13:51 UTC, valeriupredoi commented on README.md
> +download_from_mass -h
can you add this to the commands we test in `.github/workflows/run-tests.yml` as well pls?

2022-11-28 12:54 UTC, valeriupredoi requested changes

2022-11-30 11:32 UTC, valeriupredoi commented on bgcval2/download_from_mass.py
> +        shutil.copy(download_script_path, shared_file_path)
nvmnd it's just a wee file

2022-11-30 11:32 UTC, valeriupredoi commented on bgcval2/download_from_mass.py
>      if len(output.split('\n')) > 6000:
fixed it now

2022-11-30 11:32 UTC, valeriupredoi commented on README.md
> +download_from_mass -h
did it now

2022-11-30 11:35 UTC, valeriupredoi approved these changes
nice work @ledm :beer:

2022-11-30 11:35 UTC, merged