Nowmaps
valeriupredoi/bgcval2 pull request #75
Opened 2023-01-19 14:08 UTC by ledm

So this is a branch that adds a whole bunch of PML code from the Nowmaps project. This includes a bunch of ERSEM fields, and

2023-01-26 15:38 UTC, valeriupredoi commented
`analysis_p2p` has no function `p2pDict_level2` dude

2023-01-26 15:40 UTC, ledm commented
Yes, that was one of the things we've removed when we put all the key lists in yml's instead of in python dicts like `p2pDict_level2`. Surprised it is still being used anywhere?

2023-01-26 16:23 UTC, valeriupredoi commented
yeh it's imported and called twice in `bgcval.py` - wanna have a look at the failed test? See why tests are important :grin:

2023-01-31 16:49 UTC, ledm commented
So, the TF code seems to run just fine on jasmin and doesn't break anything.

Produces this report: https://gws-access.jasmin.ac.uk/public/esmeval/CompareReports/bgcval2/ldemora/TerraFIRMA_overshoot_pi_2022_NowmapsBranch/TerraFIRMA_overshoot_pi_2022/

2023-02-01 08:17 UTC, ledm commented
> `analysis_p2p` has no function `p2pDict_level2` dude.

So how do you use bgcval.py in your tests? It looks like that code is pretty full of old bgcval1 stuff we haven't needed for a while.

2023-02-01 09:46 UTC, valeriupredoi commented
> > `analysis_p2p` has no function `p2pDict_level2` dude.
> 
> So how do you use bgcval.py in your tests? It looks like that code is pretty full of old bgcval1 stuff we haven't needed for a while.

nothing fancy - just a modules import test, man. Retire it if it's ye olde (not the test, the module)

2023-02-01 09:51 UTC, valeriupredoi commented on .github/workflows/run-tests-push.yml
> +#          bgcval --help
```suggestion
```

2023-02-01 12:48 UTC, valeriupredoi commented
OK I fixed your poorly "fixed" import and run tests for `bgcval` and now the module is nicely ignored by pytest (we should completely retire it, but not in this PR). However, you introduced a couple bugs that make the end to end runs fail now, can you fix those, pls bud? See the two failed tests :beer:

2023-02-01 14:03 UTC, valeriupredoi requested changes

2023-02-01 14:04 UTC, valeriupredoi commented on tests/integration/test_analysis_compare_end-end.py
> +    with arguments('analysis_compare', '-y', 'input_yml/integration_testing.yml'):
if you want to detach the actual `debug.yml` then create a very similar one for testing, but preserve its structure so we have realistic testing

2023-02-01 14:07 UTC, valeriupredoi commented on tests/integration/test_analysis_compare_end-end.py
> +    with arguments('analysis_compare', '-y', 'input_yml/integration_testing.yml'):
incidentally `input_yml/integration_testing.yml` don't exist

2023-02-01 16:00 UTC, valeriupredoi requested changes

2023-02-01 16:00 UTC, valeriupredoi commented on bgcval2/p2p/p2pPlots.py
> +    except: calendar='gregorian'
```suggestion
    except:
        calendar='gregorian'
```

2023-02-01 16:31 UTC, valeriupredoi requested changes
wozers, the sheer volume of this PR challenged me more than your bathroom is atm :grin: Looks good, man, apart from a few wiggles that I suggested code changes for :beer:

2023-02-02 09:13 UTC, ledm commented on bgcval2/p2p/p2pPlots.py
> +        self.year = str(int(year))
It could be a float though, so float -> int -> str.

2023-02-02 09:32 UTC, ledm commented on bgcval2/analysis_timeseries.py
> +        if 'dataFiles' in av[name] or 'dataFiles' in av[name] :
```suggestion
        if 'dataFiles' in av[name] or 'dataFile' in av[name]:
```

2023-02-02 09:43 UTC, ledm commented on bgcval2/bgcvaltools/makeMask.py
> +                assert 0
Calling this a python 2 thing is kinder than this pattern deserves, lol.

2023-02-02 10:02 UTC, ledm commented on bgcval2/netcdf_manipulation/mergeNC.py
> +
To be honest, I want to replace this entire `netcdf_manip` toolkit with nctoolkit tools. Better to outsource this functionality entirely.

2023-02-02 11:25 UTC, ledm commented on bgcval2/p2p/testsuite_p2p.py
> +    everything = ukp.reducesShelves(shelvesAV)
haha.

2023-02-02 11:36 UTC, ledm reviewed
Checked everything - one file by file. Looks fine to me.

2023-02-02 11:56 UTC, ledm commented on bgcval2/netcdf_manipulation/convertToOneDNC.py
> -                    var, "not found"
Like I said, I'd like to remove this entire directory in the future,

2023-02-02 12:29 UTC, ledm commented
One of the recent changes added `scikit-learn` to the requirements. I've added it to `environment.yml`, but it looks like the tests are failing because it's not there. Does it need to be added elsewhere as well?

2023-02-02 13:10 UTC, valeriupredoi commented
> One of the recent changes added `scikit-learn` to the requirements. I've added it to `environment.yml`, but it looks like the tests are failing because it's not there. Does it need to be added elsewhere as well?

hang on, lemme have a look..

2023-02-02 13:14 UTC, valeriupredoi commented
> Checked everything - one file by file. Looks fine to me.

boss level! :beers:

2023-02-02 13:23 UTC, valeriupredoi approved these changes
[test](https://github.com/valeriupredoi/bgcval2/actions/runs/4074826843/jobs/7020432729) running fine, buds, all good by me, cheers :beers: Merge at will!

2023-02-02 13:56 UTC, merged